create table cart (cart_id bigint not null, quantity integer not null, primary key (cart_id)) engine=InnoDB;
create table cart_seq (next_val bigint) engine=InnoDB;
insert into cart_seq values ( 1 );
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_product bigint, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255), image varchar(255), name varchar(255), price float(53), quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table orders add constraint FKbbnn9yjjewm6eoqybqyyvs92r foreign key (fk_product) references products (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null, quantity integer not null, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table cart_products (cart_cart_id bigint not null, products_id bigint not null, primary key (cart_cart_id, products_id)) engine=InnoDB;
create table cart_seq (next_val bigint) engine=InnoDB;
insert into cart_seq values ( 1 );
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_product bigint, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255), image varchar(255), name varchar(255), price float(53), quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart_products add constraint UK_3kg5kx19f8oy0lo76hdhc1uw1 unique (products_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table cart_products add constraint FK7xg877l1r2f279hmlcowu1cth foreign key (products_id) references products (id);
alter table cart_products add constraint FKewu4olnfvfyd6wfdix1s4gdtr foreign key (cart_cart_id) references cart (cart_id);
alter table orders add constraint FKbbnn9yjjewm6eoqybqyyvs92r foreign key (fk_product) references products (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null, quantity integer not null, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table cart_products (cart_cart_id bigint not null, products_id bigint not null, primary key (cart_cart_id, products_id)) engine=InnoDB;
create table cart_seq (next_val bigint) engine=InnoDB;
insert into cart_seq values ( 1 );
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_product bigint, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255), image varchar(255), name varchar(255), price float(53), quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart_products add constraint UK_3kg5kx19f8oy0lo76hdhc1uw1 unique (products_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table cart_products add constraint FK7xg877l1r2f279hmlcowu1cth foreign key (products_id) references products (id);
alter table cart_products add constraint FKewu4olnfvfyd6wfdix1s4gdtr foreign key (cart_cart_id) references cart (cart_id);
alter table orders add constraint FKbbnn9yjjewm6eoqybqyyvs92r foreign key (fk_product) references products (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null, quantity integer not null, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table cart_products (cart_cart_id bigint not null, products_id bigint not null, primary key (cart_cart_id, products_id)) engine=InnoDB;
create table cart_seq (next_val bigint) engine=InnoDB;
insert into cart_seq values ( 1 );
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_product bigint, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255), image varchar(255), name varchar(255), price float(53), quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart_products add constraint UK_3kg5kx19f8oy0lo76hdhc1uw1 unique (products_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table cart_products add constraint FK7xg877l1r2f279hmlcowu1cth foreign key (products_id) references products (id);
alter table cart_products add constraint FKewu4olnfvfyd6wfdix1s4gdtr foreign key (cart_cart_id) references cart (cart_id);
alter table orders add constraint FKbbnn9yjjewm6eoqybqyyvs92r foreign key (fk_product) references products (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table cart (cart_id bigint not null auto_increment, quantity integer not null, product_id bigint, user_id bigint, primary key (cart_id)) engine=InnoDB;
create table category (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table orders (id bigint not null, address varchar(255) not null, city varchar(255) not null, county varchar(255) not null, created_at datetime, email varchar(255) not null, full_name varchar(255) not null, otherinfo varchar(255), phone_number varchar(255) not null, zip varchar(255) not null, fk_user bigint, primary key (id)) engine=InnoDB;
create table orders_products (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders_seq (next_val bigint) engine=InnoDB;
insert into orders_seq values ( 1 );
create table products (id bigint not null, category varchar(255) not null, image varchar(255) not null, name varchar(255) not null, price float(53) not null, quantity integer not null, primary key (id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table roles (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table cart add constraint UKmg7gch7630wv3d0mif6gtnsy0 unique (user_id, product_id);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table cart add constraint FKpu4bcbluhsxagirmbdn7dilm5 foreign key (product_id) references products (id);
alter table cart add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 foreign key (user_id) references users (id);
alter table orders add constraint FK8suceksxgfoqf4j1pqe6er1sh foreign key (fk_user) references users (id);
alter table orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products (id);
alter table orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
